## 1. Installation

pip install numpy

## 2. Motivation

### creating array in numpy

In [ ]:
import numpy as np

a = np.arange(10) #using arange function
print(a)

b = np.array([1,2,3,4,5]) #creating array from list
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


### why to use numpy ?

In [ ]:
L = range(1000)
%timeit [i**2 for i in L]

695 µs ± 95 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
A = np.arange(1000)
%timeit A**2

3.04 µs ± 787 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
print("Numpy implementation is {0} times faster than lists implementation".format(272/1.25))

Numpy implementation is 217.6 times faster than lists implementation


## 3. Creating arrays

### 3.1. Manual construction of the arrays

In [ ]:
#create 1 - D array #vector
a = np.array([1,2,3,4,5])

a

In [ ]:
#print dimensions
a.ndim

In [ ]:
#print shape
a.shape

In [ ]:
len(a)

In [ ]:
#create 2-D array #matrix

b = np.array([[1,2,3],[4,5,6]]) #list of lists

b

In [ ]:
b.ndim

In [ ]:
b.shape

In [ ]:
len(b) #size of first dimension or number of rows

In [ ]:
#create 3 - D array #tensors

c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

c

In [ ]:
c.ndim

In [ ]:
c.shape

In [ ]:
len(c)

### 3.2. Functions for creating arrays

In [ ]:
#using arange function

a = np.arange(10)

a

In [ ]:
b = np.arange(1,10,2) #start, end, step

b

In [ ]:
#using linspace #linearspace

c = np.linspace(5, 10, 5) #start, end, number of points

c

In [ ]:
#common arrays

d = np.ones((3,3))

d

In [ ]:
x = np.zeros((3,3))

x

In [ ]:
y = np.eye(3) #creates a matrix with 1 as the diagonals and 0 as non-diagonal elements

y

In [ ]:
z = np.eye(3,2)

z

In [ ]:
a = np.diag([1,2,3,4]) #construct a diagonal array

print(a)

In [ ]:
np.diag(a) #extracts the diagonal elements of matrix a

In [ ]:
#creates a array using random
a = np.random.rand(4)

print(a)

## 4. Datatypes

In [ ]:
#we can explicitly specify the required data type
a = np.arange(10, dtype='float')

print(a)

In [ ]:
b = np.array([1+2j, 5+1j])

print(b.dtype)

In [ ]:
c = np.array([True, False, True])

print(c.dtype)

## 5. Indexing and slicing

### 5.1. Indexing

In [ ]:
a = np.arange(10)

#print(a)
print(a[5])
print(a[-1])

In [ ]:
b = np.diag([1,2,3])

#print(b)
print(b[2,2])

In [ ]:
b[2,1] = 10 #asigning value to a index

print(b)

### 5.2. Slicing

In [ ]:
a = np.arange(10)

print(a[1:10:2]) #[start_value: end_value(exclusive): step]

In [ ]:
b = np.arange(10)

b[5:] = 10 #assign 10 from index 5 to end

print(b)

In [ ]:
c = np.arange(5)

b[5:] = c[::-1] #assign in reverse order

print(b)

## 6. Copies and views

Slicing operation creates a view on the original array which is just a way of accessing the data. Thus, the original array is not copied in the memory. You can use <strong>np.may_share_memory()</strong> to check whether two arrays share the same memory block.

In [ ]:
a = np.arange(10)

b = a[::2]

np.shares_memory(a,b)

In [ ]:
b[0] = 10

print(b)
print(a) #a is also updated, since is shares the same location in memory

In [ ]:
c = a[::2].copy() #force the copy

np.shares_memory(a,c)

In [ ]:
c[0] = 5

print(c)
print(a)

## 7. Fancy Indexing

### 7.1 Using Boolean mask

In [ ]:
a = np.random.randint(0,20,15)

print(a)

In [ ]:
mask = (a % 2 == 0)

In [ ]:
even_numbers = a[mask]

print(even_numbers)

In [ ]:
a[mask]=-1 #it can be very useful to assign a new value to sub array

print(a)

### 7.2. Using Integer Array

In [ ]:
a = np.arange(0,100,10)

print(a)

In [ ]:
b = a[[2,3,5,2,4]]

print(b)

In [ ]:
a[[9,7]] = -200

print(a)
print(b)

## 8. Numerical Operations on numpy

### 8.1. Element wise operations

In [ ]:
a = np.arange(10)

print(a+1)

In [ ]:
print(a ** 2)

In [ ]:
b = np.ones(10) + 1
print("b = ", b)

print("a - b = ",a-b)

In [ ]:
print(a*b)

In [ ]:
#Matrix Multiplication

c = np.diag([1,2,3,4])

print(c)
print("*"*100)
print(c*c)
print("*"*100)
print(c.dot(c))

In [ ]:
# element comparisions

a = np.array([1,2,5,4])
b = np.array([6,2,9,4])

print(a==b)

In [ ]:
print(a>b)

In [ ]:
print(a<b)

In [ ]:
print(a<=b)

In [ ]:
#array wise comparision

print(np.array_equal(a,b))

In [ ]:
c = np.array([1,2,5,4])

print(np.array_equal(a,c))

#### Logical Operations

In [ ]:
a = np.array([1,0,0,1],dtype='bool')
b = np.array([0,1,0,1],dtype='bool')

print(np.logical_or(a,b))

In [ ]:
print(np.logical_and(a,b))

In [ ]:
print(np.logical_not(a))

#### Transcendental Functions:

In [ ]:
a = np.arange(5)+1

print(np.sin(a))

In [ ]:
print(np.log(a))

In [ ]:
print(np.exp(a))

#### Shape Mismatch:

In [ ]:
a = np.array([1,2,3,4])

b = np.array([5, 10])

print(a+b)

### 8.2. Basic Reductions

In [ ]:
x = np.array([1,2,3,4])

print(np.sum(x))

In [ ]:
y = np.array([[1,2],[3,4]])

print(y)
print("*"*100)
print(y.T)

In [ ]:
print(y.sum(axis=0)) #column wise sum

In [ ]:
print(y.sum(axis=1)) #row wise sum

#### other reductions

In [ ]:
print(y.min())

In [ ]:
print(y.max())

In [ ]:
print(y.argmin()) #index of minimum element

In [ ]:
print(y.argmax()) #index of maximum element

#### Logical reductions

In [ ]:
print(np.all([True, False, False])) #logical and

In [ ]:
print(np.any([True, False, False])) #logical or

In [ ]:
a = np.zeros((50,50))

print(np.any(a!=0)) #checks whether any element in a is not equal to zero

#### Statistics

In [ ]:
x = np.arange(1,10)

print(np.mean(x))

In [ ]:
print(np.median(x))

In [ ]:
y = np.array([[1,2,3],[4,5,6]])

print(np.mean(y,axis=0)) #column wise mean
print(np.mean(y,axis=1)) #row wise mean

In [ ]:
print(np.std(x))

#### Example:

In [ ]:
data = np.loadtxt("dataset/populations.txt")

In [ ]:
print(data)

In [ ]:
data.shape

In [ ]:
year, hare, lynx, carrot = data.T

In [ ]:
print(year)

In [ ]:
populations = data[:,1:]

In [ ]:
print(populations)

In [ ]:
populations.std(axis=0)

In [ ]:
populations.mean(axis=0)

In [ ]:
#which species has the highest population each year

print(np.argmax(populations, axis=1))

## 9. Broadcasting

In [ ]:
from IPython.display import Image

Image("photos/broadcasting.PNG")

In [ ]:
a = np.tile(np.arange(0, 40, 10),(3,1)) #replicate rows 3 times and columns 1 time # change columns
print(a)
print("*"*100)

a = a.T
print(a)

In [ ]:
b = np.array([0,1,2])

print(b)

In [ ]:
c = a + b

print(c)

In [ ]:
a = np.arange(0,40,10)
print(a.shape)

In [ ]:
a = a[:, np.newaxis] #adds a new axis
print(a.shape)

In [ ]:
print(a)

In [ ]:
print(a+b)

## 10. Array Manipulation

### 10.1. Flattening

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

In [ ]:
print(a.ravel())

In [ ]:
print(a.T)

In [ ]:
print(a.T.ravel())

### 10.2. Reshaping

In [ ]:
print(a.shape)

In [ ]:
b = a.ravel()
print(b.shape)

In [ ]:
b = b.reshape(2,3)
print(b.shape)

### 10.3. Adding a new dimension

In [ ]:
z = np.arange(1,10,2)
print(z.shape)

In [ ]:
z = z[:,np.newaxis]
print(z.shape)

In [ ]:
z = z[:,np.newaxis]
print(z.shape)

### 10.4. Dimension Shuffling

In [ ]:
a = np.arange(4*3*2)
print(a)

In [ ]:
a = a.reshape(4,3,2) # 4 matrices of 3 rows and 2 columns each
print(a)

In [ ]:
a[3,1,1]

### 10.5. Resizing

In [ ]:
a = np.arange(5)
a.resize((10,))

### 10.6. Sorting

In [ ]:
a = np.array([[5,4,3],[2,1,9]])
print(a)

In [ ]:
b = np.sort(a, axis=1)
print(b)

In [ ]:
c = np.sort(a, axis=0)
print(c)

In [ ]:
d = a.ravel()
print(d)

In [ ]:
print(np.sort(d))

## 11. Exercises  

*(Type you code in the below cell)*

1. **Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.**

*Expected Output:*

Original List: [12.23, 13.32, 100, 36.32]

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]


2. **Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.**

*Expected Output:*

[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

3. *Write a NumPy program to sort an along the first, last axis of an array.**

Sample array: [[2,5],[4,4]]
    
*Expected Output:*
    
Original array:
[[4 6]
[2 1]]

Sort along the first axis:
[[2 1]
[4 6]]

Sort along the last axis:
[[1 2]
[4 6]]

In [ ]:
import numpy as np
a = np.array([[4, 6], [2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


4. **Write a NumPy program to create a contiguous flattened array.**

*Expected Output:*

Original array:
[[10 20 30]
[20 40 50]]

New flattened array:
[10 20 30 20 40 50]

 5. **Write a NumPy program to display all the dates for the month of March, 2017.**

*Expected Output:*

March, 2017

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
'2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
'2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
'2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
'2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
'2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
'2017-03-31']

 6. **Write a NumPy program to generate six random integers between 10 and 30.**

*Expected Output:*
    
[20 28 27 17 28 29]

7. **Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.**

*Expected Output*

Original Array:
    
[[ 0.96336355 0.12339131 0.20295196 0.37243578 0.88105252]
[ 0.93228246 0.67470158 0.38103235 0.32242645 0.40610231]
[ 0.3113495 0.31688 0.79189089 0.08676434 0.60829874]
[ 0.30360149 0.94316317 0.98142491 0.77222542 0.51532195]
[ 0.97392305 0.16669609 0.81377917 0.2165645 0.00121611]]

Minimum and Maximum Values:
    
0.00121610921757 0.981424910368

8. **Write a NumPy program to get the powers of an array values element-wise.**

Note: First array elements raised to powers from second array
    
*Expected Output:*
    
Original array

[0 1 2 3 4 5 6]

First array elements raised to powers from second array, element-wise:
    
[ 0 1 8 27 64 125 216]

9. **Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.**

*Expected Output:*

Original array:

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
(b'Pit', 5, 40.11)]

Sort by height

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
(b'Nail', 6, 52.5 )]

10. **Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.**

*Expected Output:*

Sorted indices

[4 0 5 3 6 1 2]

Sorted data:

1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0